CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  TEXT                                    NOT NULL,
    requestor_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requests_requestor
        FOREIGN KEY (requestor_id)
            REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  TEXT                                    NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    request_id   BIGINT,

    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_items_owner
        FOREIGN KEY (owner_id)
            REFERENCES users (id),

    CONSTRAINT fk_items_request
        FOREIGN KEY (request_id)
            REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_at  TIMESTAMP                               NOT NULL,
    end_at    TIMESTAMP                               NOT NULL,
    item_id   BIGINT                                  NOT NULL,
    booker_id BIGINT                                  NOT NULL,
    status    VARCHAR(32)                             NOT NULL,

    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_bookings_item
        FOREIGN KEY (item_id)
            REFERENCES items (id),

    CONSTRAINT fk_bookings_booker
        FOREIGN KEY (booker_id)
            REFERENCES users (id),

    CONSTRAINT chk_booking_dates
        CHECK (end_at > start_at),

    CONSTRAINT chk_booking_status
        CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      TEXT                                    NOT NULL,
    created   TIMESTAMP                               NOT NULL,
    item_id   BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,

    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comments_item
        FOREIGN KEY (item_id)
            REFERENCES items (id),

    CONSTRAINT fk_comments_author
        FOREIGN KEY (author_id)
            REFERENCES users (id)
);



